### ISSUE TITLE
Where to place .htaccess for mod_rewrite

### ISSUE THREAD

**Issue by onlineth** [pinodex/openshift-cartridge-nginx-php7#10]
Hi, I have an .htaccess file that reads like this:

``` apache
RewriteEngine on
RewriteRule ^(.*)\.png script.php

Options -Indexes
```

Where should I place this file and does this cartridge support mod_rewrite?

Thanks,

Thomas

**Comment by pinodex** [comment]
`.htaccess` is not supported here. The cartridge uses Nginx as the webserver. Check the [documentation](http://nginx.org/en/docs/http/converting_rewrite_rules.html) on converting Apache rewrite rules to Nginx rewrite rules.

**Comment by onlineth** [comment]
I see, I've just modified the /config/nginx.d/default.conf.erb file and added:

``` nginx
    # Rewrite all png images to go to the script
    location ~* \.png {
        rewrite ^(.*)\\.png$ /script.php;
    }
```

That seemed to do the trick, is it ok to modify the default config file? Could it be potentially erased upon the `update` command?

**Comment by pinodex** [comment]
Yes, that should do it. It won't be touched when updating the cartridge.

**Comment by onlineth** [comment]
Great, thanks:)
