### ISSUE TITLE
I found some necessary extensions missing when trying to use composer 

### ISSUE THREAD

**Issue by educate** [pinodex/openshift-cartridge-nginx-php7#11]
Hi,
You said composer has been warpped in the cartridge, well, I still don't know how to use it after removing hash key in the front of 
`#cd $OPENSHIFT_REPO_DIR; composer install`
then I decided to download it by running command
`curl -s http://getcomposer.org/installer | php`

Unfortunately, it gave out error messages as follow
The json extension is missing.
Install it or recompile php without --disable-json

The phar extension is missing.
Install it or recompile php without --disable-phar

The iconv OR mbstring extension is required and both are missing.
Install either of them or recompile php without --disable-iconv

The extensions mentioned above were not loaded, `php -m`, have they installed correctly?

Best regards,
Ethan

**Comment by khurshid-alam** [comment]
@pinodex Is this issue resolved?

**Comment by pinodex** [comment]
Sorry for the late reply. Are you still experiencing the issue?

**Comment by educate** [comment]
Sorry, I am not an experienced user for this, I may be wrong in the first place, If you've tested and find the problem doesn't exist, please close this issue.

**Comment by pinodex** [comment]
I tested this and it is working. Thanks!
