### ISSUE TITLE
If connect via SFTP where is the www dir located?

### ISSUE THREAD

**Issue by Velliz** [pinodex/openshift-cartridge-nginx-php7#12]
Hi, I successfully push the code via git.
But now i join team and work with a front end developer. But he only want to access the app using SFTP connection.

I succesfully connect via SFTP but don't know where the www folder exists because when previewing linux dir floder i always got 'access denied'.

Thanks, 
Didit Velliz.

**Comment by pinodex** [comment]
It is `~/app-root/repo/www`. Though I wouldn't recommend writing directly to that directory because it will be overwritten on every git push.

**Comment by Velliz** [comment]
Ok. Thanks!
I got it.
