### ISSUE TITLE
"v" parameter to specifiy witch version of PHP to install

### ISSUE THREAD

**Issue by Velliz** [pinodex/openshift-cartridge-nginx-php7#13]
Hello.

In your prev project 'openshift-nginx-php-fpm'
I see you introduce "v" parameter to specifiy witch version of PHP to install.

can you added the feature to 'openshift-cartridge-nginx-php7'?
because when i creating new cartridges (release 1.8.0) i have array bug in PHP 7.0.11 version.

[bug 73125](https://bugs.php.net/bug.php?id=73125)
[bug 73232](https://bugs.php.net/bug.php?id=73232)

and it was no problem for my prev project with cartridges (release 1.7.0) with PHP 7.0.9

Thanks.

**Comment by pinodex** [comment]
Hi. Sorry for the late reply.

I can't add that feature, but I'm going to update the packages in a moment.

**Comment by Velliz** [comment]
No problem. 
I already fix it with fork your repo and rollback it to Cartridge Version 1.7.0 and all is well now :D

**Comment by pinodex** [comment]
Alright. Closing this issue now. Thanks!
