### ISSUE TITLE
php 7.0.5

### ISSUE THREAD

**Issue by BrainOfJ** [pinodex/openshift-cartridge-nginx-php7#2]
Sorry to bother but you should update to .5, .4 has some [nasty bugs](https://bugs.php.net/bug.php?id=71756).
I tried to do it for myself, but I can't get PHP to build.

**Comment by pinodex** [comment]
Looking on that now.

**Comment by pinodex** [comment]
PHP has been updated to 7.0.5. Can you please confirm if it is working on your end?

Also, we currently don't have a way of automating the cartridge update process. You can either reinstall the application or patch the changed files from @c699a578f3c34c9cda474f1ec417643e29a78c38.

Thanks.

**Comment by BrainOfJ** [comment]
Confirmed working, including Composer. Thank you for your time.

**Comment by pinodex** [comment]
Thank you and no problem.
