### ISSUE TITLE
MongoDB Driver

### ISSUE THREAD

**Issue by mops1k** [pinodex/openshift-cartridge-nginx-php7#3]
Hi!
Can you tell me how to install mongodb php driver in this cartrige or can you include it inside?

**Comment by pinodex** [comment]
Put the `.so` file inside `usr/lib64/php/modules/`. But it will be lost after a cartridge update as it does remove and replace the `usr/` directory.

Then edit your `config/php.d/extensions.ini` and add 

```
extension=mongodb.so
```

I'm having troubles with mongodb driver before so I did not included it. I'll try if I can make it work now. If you can make it work, please submit a pull request.

**Comment by mops1k** [comment]
Ok, thanks for answer.

**Comment by pinodex** [comment]
I got it working. I will be releasing an update in a moment.

**Comment by pinodex** [comment]
I added the MongoDB driver.

Just update your cartridge and add/uncomment this line from your repo's `config/php.d/extensions.ini`:

```
extension=mongodb.so
```

**Comment by mops1k** [comment]
Thanks a lot! Now my Symfony app will work :)
