### ISSUE TITLE
Site are Not Loading after using SSL

### ISSUE THREAD

**Issue by rpsadarangani** [pinodex/openshift-cartridge-nginx-php7#5]
Hello,

Thanks for this excellent script it's working fantastically, but I don't when I try to use SSL it is giving an SSL Redirect issue any idea how to solve this problem. If using SSL the Error is "redirected you too many times."

**Comment by pinodex** [comment]
Are you using a custom domain or an rhcloud.com subdomain? Do you have redirect rules set up to redirect http to https?

**Comment by rpsadarangani** [comment]
rhcloud.com have not tried custom domain as I am designing my application

**Comment by pinodex** [comment]
I never had that problem. Can you please provide steps to reproduce the issue? Screenshots and config files might also help.

**Comment by rpsadarangani** [comment]
Here is the Website URL https://iyercommerceclasses-webdomin.rhcloud.com/ it is having WordPress install and it is creating redirect loop I have tried all the WordPress measure which need to taken care but then also not working. I have migrated the website from share hosting

**Comment by pinodex** [comment]
Try editing your `wp-config.php` file, and adding these lines above the `/* That's all, stop editing! Happy blogging. */`

```
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['HTTPS'] = 'on';
}
```

**Comment by rpsadarangani** [comment]
Thanks the issue got solved One More question how where does .htaccess need to put as I am not able to find it and also how can I update PHP Setting

**Comment by rpsadarangani** [comment]
Because Permalink are not working and need to update some of upload setting

**Comment by pinodex** [comment]
`.htaccess` won't work here because it uses Nginx instead of Apache. Look up the docs on setting rewrite rules for WordPress in Nginx.

For editing the PHP configuration, you can put your own `.ini` file at your repo's `config/php.d/` directory, and overwrite the previously defined settings. You can also SSH to your app, and edit the main PHP configuration file at `~/nginx-php7/etc/php.ini.erb`. Be sure to run `build_config` command and restart php-fpm after (see [README.md#scripts](https://github.com/pinodex/openshift-cartridge-nginx-php7/blob/master/README.md#scripts)).

**Comment by rpsadarangani** [comment]
Any Idea where can I Find them

**Comment by pinodex** [comment]
Sorry for the late reply. There's Nginx docs you can easily look into.

**Comment by rpsadarangani** [comment]
Thanks, It Started Working Was Testing for Past 2 Builds. I came up with a Small issue this morning when Nginx Configuration was automatically restored to default. Any Idea Why Did that Happen.

**Comment by pinodex** [comment]
Is it the `config/nginx.d/default.conf[.erb]`? Did you edited it inside your app (SSH)? It should be edited in your local repository instead, then push the changes to the remote repository. Any changes inside `app-root/repo/` will always be overwritten by what you pushed to the remote repository.

I provided the steps on editing your nginx config which may help you:
1. Browse your local repository, and open the `config/nginx.d/default.conf.erb`
2. Make any changes you want then save
3. Stage the changed file (`git add config/nginx.d/default.conf.erb`)
3. Commit your local changes (`git commit -m "Edited nginx config`)
4. Push to remote repository (`git push origin master`)
