### ISSUE TITLE
session_write_close(): Failed to write session data (files)

### ISSUE THREAD

**Issue by skywalker512** [pinodex/openshift-cartridge-nginx-php7#8]
session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/openshift/***_/app-root/data//php-session) in ***_*
There didn't have '***data//php-session' should add by myself.

**Comment by colinwilson** [comment]
Just experienced this myself while installing Craft CMS. Created the `php-session` directory and everything worked.

**EDIT**

Please correct me if I'm wrong.

The PHP `save.session_path` set in `/etc/www.conf.erb`:

 `php_value[session.save_path] = <%= ENV['OPENSHIFT_DATA_DIR'] %>/php-session`

doesn't  match up with the session directory created in `/bin/setup`

`mkdir -p ${OPENSHIFT_PHP_DIR}{logs,run,tmp,sessions}`

**Comment by pinodex** [comment]
Sorry for the delay. This has been fixed in the latest cartridge release.
