### ISSUE TITLE
Keep .env file

### ISSUE THREAD

**Issue by reina3596** [pinodex/openshift-cartridge-nginx-php7#9]
Helo Pinodex,

I am using your cartridge for development of Laravel 5.3.

I know how you execute automatic composer install in each "git push".

¿Can I keep my .env file? I have in .gitignore but in each "git push" the file is erase. I need keep this file for configuration database openshift.

Sorry for my English

**Comment by pinodex** [comment]
Remove the `.env` line in your `.gitignore` file. Then add the file to git.

**Comment by reina3596** [comment]
I have found other solution.

I hace created a .envió.openshift file with the correct configuration for my app.

In the action_hook I have add an "cp .env.openshift .env".

When I do git push. All changes are uploaded and the correct file .env restored.

;)

Best Regards!!!

**Comment by pinodex** [comment]
Closing this issue now.
